# Generated by Django 2.2.10 on 2026-01-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/', verbose_name='Upload Resumes')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tag')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mobile Number')),
                ('education', models.CharField(blank=True, max_length=255, null=True, verbose_name='Education')),
                ('skills', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Skills')),
                ('company_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Company Name')),
                ('college_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='College Name')),
                ('designation', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Designation')),
                ('experience', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Experience')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded On')),
                ('total_experience', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Total Experience (in Years)')),
                ('ai_summary', models.TextField(blank=True, null=True, verbose_name='AI Summary')),
                ('ai_strengths', models.TextField(blank=True, null=True, verbose_name='AI Strengths')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='Processing Time (seconds)')),
                ('remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Remark')),
            ],
        ),
    ]
