# Generated by Django 2.2 on 2019-10-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0010_resume_competencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='competencies',
        ),
        migrations.AddField(
            model_name='resume',
            name='college_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='College Name'),
        ),
        migrations.AddField(
            model_name='resume',
            name='company_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='resume',
            name='designation',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Designation'),
        ),
        migrations.AddField(
            model_name='resume',
            name='total_experience',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Total Experience (in Years)'),
        ),
    ]
