# Generated by Django 2.2.10 on 2025-12-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0011_auto_20191022_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tag'),
        ),
    ]
