# Generated by Django 2.1.4 on 2019-04-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0011_auto_20190419_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumedetails',
            name='page_nos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Pages'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='years_of_exp',
            field=models.FloatField(blank=True, null=True, verbose_name='Experience'),
        ),
    ]
