# Generated by Django 2.2.10 on 2025-12-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0012_resume_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='remark',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Remark'),
        ),
    ]
