# Generated by Django 2.2.10 on 2026-01-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0013_resume_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='ai_strengths',
            field=models.TextField(blank=True, null=True, verbose_name='AI Strengths'),
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_summary',
            field=models.TextField(blank=True, null=True, verbose_name='AI Summary'),
        ),
    ]
