# Generated by Django 2.2.10 on 2026-01-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0014_auto_20260107_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='processing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Processing Time (seconds)'),
        ),
    ]
