# Generated by Django 2.2.10 on 2026-01-30 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '0003_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(choices=[('SCREENING', 'Screening'), ('TECHNICAL', 'Technical'), ('MANAGERIAL', 'Managerial'), ('HR', 'HR Round'), ('FINAL', 'Final Decision')], default='SCREENING', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('date_time', models.DateTimeField()),
                ('link', models.URLField(blank=True, help_text='Zoom/Meet Link', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='candidates.Application')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
