# Generated by Django 2.2.10 on 2026-01-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ai_strengths',
            field=models.TextField(blank=True, help_text='Key Strengths', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI Generated Summary', null=True),
        ),
    ]
