# Generated by Django 2.2.10 on 2026-02-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_auto_20260130_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SCREENED', 'Screened'), ('INTERVIEW', 'Interviewing'), ('OFFERED', 'Offered'), ('REJECTED', 'Rejected'), ('HIRED', 'Hired')], db_index=True, default='APPLIED', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('PLACED', 'Placed')], db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
