# Generated by Django 2.2.10 on 2026-02-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='processing_time',
            field=models.FloatField(default=0.0, help_text='Time taken to parse in seconds'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='remark',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
